
package br.com.projeto.view;

import br.com.projeto.dao.ClienteDao;
import br.com.projeto.model.Cliente;
import br.com.projeto.model.Uteis;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edersom Denir Giacomelli
 */
public class frmcliente extends javax.swing.JFrame {
    
    //método para listar na tabela
    public void listar(){
        //criar a lista de clientes
        ClienteDao dao = new ClienteDao();
        List<Cliente> lista = dao.listarClientes();
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)TabelaClientes.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Cliente coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getNome(),
                coluna.getRg(),
                coluna.getCpf(),
                coluna.getEmail(),
                coluna.getTelefone(),
                coluna.getCelular(),
                coluna.getCep(),
                coluna.getEndereco(),
                coluna.getNumero(),
                coluna.getComplemento(),
                coluna.getBairro(),
                coluna.getCidade(),
                coluna.getEstado()             
            });
        }
    }

    /**
     * Creates new form frmcliente
     */
    public frmcliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PainelDeAbas = new javax.swing.JTabbedPane();
        PainelEdicao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CxCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CxNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CxEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CxCelular = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        CxTelefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        CxCep = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        CxEndereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CxNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CxBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CxCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CxComplemento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BoxEstado = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        CxCpf = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        CxRg = new javax.swing.JFormattedTextField();
        BtnPesquisarCpf = new javax.swing.JButton();
        PainelBusca = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        CxConsulta = new javax.swing.JTextField();
        BtnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();
        BtnNovo = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(169, 199, 208));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        PainelEdicao.setBackground(new java.awt.Color(199, 223, 236));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Código cliente:");

        CxCodigo.setEditable(false);
        CxCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxCodigoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome cliente:");

        CxNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxNomeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("E-mail cliente:");

        CxEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxEmailActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Celular:");

        try {
            CxCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CxCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Telefone Fixo:");

        try {
            CxTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CxTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CEP:");

        try {
            CxCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## . ### - ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CxCep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Endereço:");

        CxEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxEnderecoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nº:");

        CxNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxNumeroActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Bairro:");

        CxBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxBairroActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("UF:");

        CxCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxCidadeActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Complemento:");

        CxComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxComplementoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Cidade:");

        BoxEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RR", "RO", "RJ", "RN", "RS", "SC", "SP", "SE", "TO" }));
        BoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxEstadoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("CPF:");

        try {
            CxCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### . ### . ### - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CxCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("RG:");

        try {
            CxRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## . ### . ### - #")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CxRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        BtnPesquisarCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnPesquisarCpf.setText("Pesquisar");
        BtnPesquisarCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelEdicaoLayout = new javax.swing.GroupLayout(PainelEdicao);
        PainelEdicao.setLayout(PainelEdicaoLayout);
        PainelEdicaoLayout.setHorizontalGroup(
            PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CxEmail)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(CxRg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(CxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnPesquisarCpf)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PainelEdicaoLayout.setVerticalGroup(
            PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(CxCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CxCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(CxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CxComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(CxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(CxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CxRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesquisarCpf))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        PainelDeAbas.addTab("Dados pessoais", PainelEdicao);

        PainelBusca.setBackground(new java.awt.Color(199, 223, 226));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nome:");

        CxConsulta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxConsultaActionPerformed(evt);
            }
        });
        CxConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CxConsultaKeyPressed(evt);
            }
        });

        BtnConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnConsultar.setText("Pesquisar");
        BtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarActionPerformed(evt);
            }
        });

        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código cliente:", "Nome cliente:", "RG:", "CPF:", "E-mail cliente:", "Telefone Fixo:", "Celular:", "CEP:", "Endereço:", "nº:", "Complemento:", "Bairro:", "Cidade:", "UF:"
            }
        ));
        TabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaClientes);

        javax.swing.GroupLayout PainelBuscaLayout = new javax.swing.GroupLayout(PainelBusca);
        PainelBusca.setLayout(PainelBuscaLayout);
        PainelBuscaLayout.setHorizontalGroup(
            PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelBuscaLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnConsultar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PainelBuscaLayout.setVerticalGroup(
            PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnConsultar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        PainelDeAbas.addTab("Consultar clientes", PainelBusca);

        BtnNovo.setBackground(new java.awt.Color(200, 200, 200));
        BtnNovo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnNovo.setForeground(new java.awt.Color(0, 0, 51));
        BtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo-documento.png"))); // NOI18N
        BtnNovo.setText("NOVO");
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BtnSalvar.setBackground(new java.awt.Color(200, 200, 200));
        BtnSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnSalvar.setForeground(new java.awt.Color(0, 0, 51));
        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar_1.png"))); // NOI18N
        BtnSalvar.setText("SALVAR");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnEditar.setBackground(new java.awt.Color(200, 200, 200));
        BtnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(0, 0, 51));
        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar (1).png"))); // NOI18N
        BtnEditar.setText("EDITAR");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnExcluir.setBackground(new java.awt.Color(200, 200, 200));
        BtnExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnExcluir.setForeground(new java.awt.Color(0, 0, 51));
        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir_1.png"))); // NOI18N
        BtnExcluir.setText("EXCLUIR");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelDeAbas)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(BtnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BtnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnEditar, BtnExcluir, BtnNovo, BtnSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelDeAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNovo)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnEditar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnEditar, BtnExcluir, BtnNovo, BtnSalvar});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxCodigoActionPerformed

    private void CxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxNomeActionPerformed

    private void CxEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxEmailActionPerformed

    private void CxEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxEnderecoActionPerformed

    private void CxNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxNumeroActionPerformed

    private void CxBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxBairroActionPerformed

    private void CxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxCidadeActionPerformed

    private void CxComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxComplementoActionPerformed

    private void CxConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxConsultaActionPerformed

    private void BtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarActionPerformed
        //Botão pesquisar
        String nome = "%" + CxConsulta.getText() + "%";
        //criar a lista de clientes
        ClienteDao dao = new ClienteDao();
        List<Cliente> lista = dao.buscarClientesPorNome(nome);
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)TabelaClientes.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Cliente coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getNome(),
                coluna.getRg(),
                coluna.getCpf(),
                coluna.getEmail(),
                coluna.getTelefone(),
                coluna.getCelular(),
                coluna.getCep(),
                coluna.getEndereco(),
                coluna.getNumero(),
                coluna.getComplemento(),
                coluna.getBairro(),
                coluna.getCidade(),
                coluna.getEstado()             
            });
        }
        
    }//GEN-LAST:event_BtnConsultarActionPerformed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        // Botão novo - limpa a tela
        new Uteis().LimparTela(PainelEdicao);
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        //Botão excluir
            //vai pegar o nome que está nas caixas
            Cliente obj = new Cliente();
            obj.setId(Integer.parseInt(CxCodigo.getText()));
            
            ClienteDao dao = new ClienteDao();
            
            dao.excluirCliente(obj);
            
            new Uteis().LimparTela(PainelEdicao);
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        // botão salvar
            //vai pegar o nome que está nas caixas
            Cliente obj = new Cliente();
            obj.setNome(CxNome.getText());
            obj.setRg(CxRg.getText());
            obj.setCpf(CxCpf.getText());
            obj.setEmail(CxEmail.getText());
            obj.setTelefone(CxTelefone.getText());
            obj.setCelular(CxCelular.getText());
            obj.setCep(CxCep.getText());
            obj.setEndereco(CxEndereco.getText());
            obj.setNumero(Integer.parseInt(CxNumero.getText()));
            obj.setComplemento(CxComplemento.getText());
            obj.setBairro(CxBairro.getText());
            obj.setCidade(CxCidade.getText());
            obj.setEstado(BoxEstado.getSelectedItem().toString());
            
            ClienteDao dao = new ClienteDao();
            
            dao.cadastrarCliente(obj);
            
            new Uteis().LimparTela(PainelEdicao);
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // Botão editar
            //vai pegar o nome que está nas caixas
            Cliente obj = new Cliente();
            obj.setNome(CxNome.getText());
            obj.setRg(CxRg.getText());
            obj.setCpf(CxCpf.getText());
            obj.setEmail(CxEmail.getText());
            obj.setTelefone(CxTelefone.getText());
            obj.setCelular(CxCelular.getText());
            obj.setCep(CxCep.getText());
            obj.setEndereco(CxEndereco.getText());
            obj.setNumero(Integer.parseInt(CxNumero.getText()));
            obj.setComplemento(CxComplemento.getText());
            obj.setBairro(CxBairro.getText());
            obj.setCidade(CxCidade.getText());
            obj.setEstado(BoxEstado.getSelectedItem().toString());
            
            obj.setId(Integer.parseInt(CxCodigo.getText()));
            
            ClienteDao dao = new ClienteDao();
            
            dao.alterarCliente(obj);
            
            new Uteis().LimparTela(PainelEdicao);
        
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxEstadoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Carrega a lista
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void TabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClientesMouseClicked
        //Pegar os dados
        //Faz voltar na tela de cadastro
        PainelDeAbas.setSelectedIndex(0);
        //Passar os dados da tabela para a tela de cadastro
        CxCodigo.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 0).toString());
        CxNome.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 1).toString());
        CxRg.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 2).toString());
        CxCpf.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 3).toString());
        CxEmail.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 4).toString());
        CxTelefone.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 5).toString());
        CxCelular.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 6).toString());
        CxCep.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 7).toString());
        CxEndereco.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 8).toString());
        CxNumero.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 9).toString());
        CxComplemento.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 10).toString());
        CxBairro.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 11).toString());
        CxCidade.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 12).toString());
        BoxEstado.setSelectedItem(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 13).toString());
    }//GEN-LAST:event_TabelaClientesMouseClicked

    private void CxConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CxConsultaKeyPressed
       //consulta apenas digitando
       String nome = "%" + CxConsulta.getText() + "%";
        //criar a lista de clientes
        ClienteDao dao = new ClienteDao();
        List<Cliente> lista = dao.buscarClientesPorNome(nome);
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)TabelaClientes.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Cliente coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getNome(),
                coluna.getRg(),
                coluna.getCpf(),
                coluna.getEmail(),
                coluna.getTelefone(),
                coluna.getCelular(),
                coluna.getCep(),
                coluna.getEndereco(),
                coluna.getNumero(),
                coluna.getComplemento(),
                coluna.getBairro(),
                coluna.getCidade(),
                coluna.getEstado()             
            });
        }
    }//GEN-LAST:event_CxConsultaKeyPressed

    private void BtnPesquisarCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarCpfActionPerformed
        // Botão de pesquisa por CPF
            String cpf = CxCpf.getText();
            Cliente obj = new Cliente();
            ClienteDao dao = new ClienteDao();
            
            obj = dao.consultarPorCpf(cpf);
            
            //Exibição de dados nos campos
            if (obj.getCpf() != null) {
            CxCodigo.setText(String.valueOf(obj.getId()));
            CxNome.setText(obj.getNome());
            CxRg.setText(obj.getRg());
            CxCpf.setText(obj.getCpf());
            CxEmail.setText(obj.getEmail());
            CxTelefone.setText(obj.getTelefone());
            CxCelular.setText(obj.getCelular());
            CxCep.setText(obj.getCep());
            CxEndereco.setText(obj.getEndereco());
            CxNumero.setText(String.valueOf (obj.getNumero()));
            CxComplemento.setText(obj.getComplemento());
            CxBairro.setText(obj.getBairro());
            CxCidade.setText(obj.getCidade());
            BoxEstado.setSelectedItem(obj.getEstado());
            }
            if (obj.getCpf() == null) {
                JOptionPane.showMessageDialog(null, "Cliente não localizado!!!");
            }
    }//GEN-LAST:event_BtnPesquisarCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmcliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxEstado;
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnPesquisarCpf;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JTextField CxBairro;
    private javax.swing.JFormattedTextField CxCelular;
    private javax.swing.JFormattedTextField CxCep;
    private javax.swing.JTextField CxCidade;
    private javax.swing.JTextField CxCodigo;
    private javax.swing.JTextField CxComplemento;
    private javax.swing.JTextField CxConsulta;
    private javax.swing.JFormattedTextField CxCpf;
    private javax.swing.JTextField CxEmail;
    private javax.swing.JTextField CxEndereco;
    private javax.swing.JTextField CxNome;
    private javax.swing.JTextField CxNumero;
    private javax.swing.JFormattedTextField CxRg;
    private javax.swing.JFormattedTextField CxTelefone;
    private javax.swing.JPanel PainelBusca;
    private javax.swing.JTabbedPane PainelDeAbas;
    private javax.swing.JPanel PainelEdicao;
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
