
package br.com.projeto.view;

import br.com.projeto.dao.ClienteDao;
import br.com.projeto.dao.FornecedorDao;
import br.com.projeto.dao.ProdutosDao;
import br.com.projeto.model.Cliente;
import br.com.projeto.model.Fornecedor;
import br.com.projeto.model.Produto;
import br.com.projeto.model.Uteis;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edersom Denir Giacomelli
 */
public class frmproduto extends javax.swing.JFrame {
    
    //método para listar na tabela
    public void listar(){
        //criar a lista de Produtos
        ProdutosDao dao = new ProdutosDao();
        List<Produto> lista = dao.listarProdutos();
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)TabelaProdutos.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Produto coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getDescricao(),
                coluna.getPreco(),
                coluna.getQtd_estoque(),
                coluna.getFornecedor().getNome()
            });
        }
    }

    /**
     * Creates new form frmcliente
     */
    public frmproduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PainelDeAbas = new javax.swing.JTabbedPane();
        PainelEdicao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CxCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cxDescricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cxEstoque = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnPesquisarNome = new javax.swing.JButton();
        boxFornecedor = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        cxPreco = new javax.swing.JTextField();
        PainelBusca = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        CxConsultaProduto = new javax.swing.JTextField();
        BtnConsultarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProdutos = new javax.swing.JTable();
        BtnNovo = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(169, 199, 208));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Cadastro de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        PainelEdicao.setBackground(new java.awt.Color(199, 223, 226));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Código Produto:");

        CxCodigo.setEditable(false);
        CxCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxCodigoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        cxDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cxDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDescricaoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Preço: ");

        cxEstoque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cxEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxEstoqueActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Estoque atual:");

        BtnPesquisarNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnPesquisarNome.setText("Pesquisar");
        BtnPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarNomeActionPerformed(evt);
            }
        });

        boxFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxFornecedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                boxFornecedorAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        boxFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxFornecedorMouseClicked(evt);
            }
        });
        boxFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFornecedorActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Fornecedor:");

        cxPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cxPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelEdicaoLayout = new javax.swing.GroupLayout(PainelEdicao);
        PainelEdicao.setLayout(PainelEdicaoLayout);
        PainelEdicaoLayout.setHorizontalGroup(
            PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(CxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                                .addComponent(cxPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cxEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                                .addComponent(cxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnPesquisarNome))))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        PainelEdicaoLayout.setVerticalGroup(
            PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesquisarNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cxEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cxPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        PainelDeAbas.addTab("Dados do Produto", PainelEdicao);

        PainelBusca.setBackground(new java.awt.Color(199, 223, 226));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Descrição:");

        CxConsultaProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxConsultaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxConsultaProdutoActionPerformed(evt);
            }
        });
        CxConsultaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CxConsultaProdutoKeyPressed(evt);
            }
        });

        BtnConsultarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnConsultarProduto.setText("Pesquisar");
        BtnConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarProdutoActionPerformed(evt);
            }
        });

        TabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código:", "Descrição:", "Preço:", "Estoque atual:", "Fornecedor:"
            }
        ));
        TabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaProdutos);

        javax.swing.GroupLayout PainelBuscaLayout = new javax.swing.GroupLayout(PainelBusca);
        PainelBusca.setLayout(PainelBuscaLayout);
        PainelBuscaLayout.setHorizontalGroup(
            PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelBuscaLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(CxConsultaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnConsultarProduto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelBuscaLayout.setVerticalGroup(
            PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CxConsultaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnConsultarProduto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        PainelDeAbas.addTab("Consultar Produtos", PainelBusca);

        BtnNovo.setBackground(new java.awt.Color(200, 200, 200));
        BtnNovo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnNovo.setForeground(new java.awt.Color(0, 0, 51));
        BtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo-documento.png"))); // NOI18N
        BtnNovo.setText("NOVO");
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BtnSalvar.setBackground(new java.awt.Color(200, 200, 200));
        BtnSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnSalvar.setForeground(new java.awt.Color(0, 0, 51));
        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar_1.png"))); // NOI18N
        BtnSalvar.setText("SALVAR");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnEditar.setBackground(new java.awt.Color(200, 200, 200));
        BtnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(0, 0, 51));
        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar (1).png"))); // NOI18N
        BtnEditar.setText("EDITAR");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnExcluir.setBackground(new java.awt.Color(200, 200, 200));
        BtnExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnExcluir.setForeground(new java.awt.Color(0, 0, 51));
        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir_1.png"))); // NOI18N
        BtnExcluir.setText("EXCLUIR");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelDeAbas)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BtnExcluir)
                .addGap(155, 155, 155))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnEditar, BtnExcluir, BtnNovo, BtnSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelDeAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNovo)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnEditar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnEditar, BtnExcluir, BtnNovo, BtnSalvar});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxCodigoActionPerformed

    private void cxDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDescricaoActionPerformed

    private void cxEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxEstoqueActionPerformed

    private void CxConsultaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxConsultaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxConsultaProdutoActionPerformed

    private void BtnConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarProdutoActionPerformed
        //Botão pesquisar
        String nome = "%" + CxConsultaProduto.getText() + "%";
        //criar a lista de clientes
        ProdutosDao dao = new ProdutosDao();
        List<Produto> lista = dao.listarProdutosPorNome(nome);
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)TabelaProdutos.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Produto coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getDescricao(),
                coluna.getPreco(),
                coluna.getQtd_estoque(),
                coluna.getFornecedor().getNome()             
            });
        }
        
    }//GEN-LAST:event_BtnConsultarProdutoActionPerformed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        // Botão novo - limpa a tela
        new Uteis().LimparTela(PainelEdicao);
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        //Botão excluir
            //vai pegar o nome que está nas caixas
            Produto obj = new Produto();
            obj.setId(Integer.parseInt(CxCodigo.getText()));
            
            ProdutosDao dao = new ProdutosDao();
            
            dao.excluir(obj);
            
            new Uteis().LimparTela(PainelEdicao);
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        // botão salvar
            //vai pegar o nome que está nas caixas
            Produto obj = new Produto();
            obj.setDescricao(cxDescricao.getText());
            obj.setPreco(Double.parseDouble(cxPreco.getText()));
            obj.setQtd_estoque(Integer.parseInt(cxEstoque.getText()));
            
            //criação de objeto de fornecedor
            Fornecedor f = new Fornecedor();
            f = (Fornecedor)boxFornecedor.getSelectedItem();
            obj.setFornecedor(f);
                        
            ProdutosDao dao = new ProdutosDao();
            
            dao.cadastrar(obj);
            
            new Uteis().LimparTela(PainelEdicao);
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // Botão editar
            //vai pegar o nome que está nas caixas
            Produto obj = new Produto();
            
            obj.setId(Integer.parseInt(CxCodigo.getText()));
            obj.setDescricao(cxDescricao.getText());
            obj.setPreco(Double.parseDouble(cxPreco.getText()));
            obj.setQtd_estoque(Integer.parseInt(cxEstoque.getText()));
            
            //criação de objeto de fornecedor
            Fornecedor f = new Fornecedor();
            f = (Fornecedor)boxFornecedor.getSelectedItem();
            obj.setFornecedor(f);
                        
            ProdutosDao dao = new ProdutosDao();
            
            dao.alterar(obj);
            
            new Uteis().LimparTela(PainelEdicao);
        
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Carrega a lista
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void TabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaProdutosMouseClicked
        //Pegar os dados
        //Faz voltar na tela de cadastro
        PainelDeAbas.setSelectedIndex(0);
        //Passar os dados da tabela para a tela de cadastro
        CxCodigo.setText(TabelaProdutos.getValueAt(TabelaProdutos.getSelectedRow(), 0).toString());
        cxDescricao.setText(TabelaProdutos.getValueAt(TabelaProdutos.getSelectedRow(), 1).toString());
        cxPreco.setText(TabelaProdutos.getValueAt(TabelaProdutos.getSelectedRow(),2).toString());
        cxEstoque.setText(TabelaProdutos.getValueAt(TabelaProdutos.getSelectedRow(), 3).toString());
        
        Fornecedor f = new Fornecedor();
        FornecedorDao dao = new FornecedorDao();
        
        f = dao.consultarPorNome(TabelaProdutos.getValueAt(TabelaProdutos.getSelectedRow(), 4).toString());
        
        boxFornecedor.removeAllItems();
        boxFornecedor.setSelectedItem(f);
        
    }//GEN-LAST:event_TabelaProdutosMouseClicked

    private void CxConsultaProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CxConsultaProdutoKeyPressed
       //consulta apenas digitando
       String nome = "%" + CxConsultaProduto.getText() + "%";
        //criar a lista de clientes
        //criar a lista de clientes
        ProdutosDao dao = new ProdutosDao();
        List<Produto> lista = dao.listarProdutosPorNome(nome);
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)TabelaProdutos.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Produto coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getDescricao(),
                coluna.getPreco(),
                coluna.getQtd_estoque(),
                coluna.getFornecedor().getNome()             
            });
        }
    }//GEN-LAST:event_CxConsultaProdutoKeyPressed

    private void BtnPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarNomeActionPerformed
        // Botão de pesquisa por CPF
            String nome = cxDescricao.getText();
            Produto obj = new Produto();
            ProdutosDao dao = new ProdutosDao();
            
            obj = dao.consultarProdutosPorNome(nome);
            
            boxFornecedor.removeAllItems();
            
            //Exibição de dados nos campos
            if (obj.getDescricao() != null) {
            CxCodigo.setText(String.valueOf(obj.getId()));
            cxDescricao.setText(obj.getDescricao());
            cxPreco.setText(String.valueOf(obj.getPreco()));
            cxEstoque.setText(String.valueOf(obj.getQtd_estoque()));
            
            Fornecedor f = new Fornecedor();
            FornecedorDao fdao = new FornecedorDao();
            
            f = fdao.consultarPorNome(obj.getFornecedor().getNome());
            
            boxFornecedor.getModel().setSelectedItem(f);
            }
            if (obj.getDescricao()== null) {
                JOptionPane.showMessageDialog(null, "Produto não localizado!!!");
            }
    }//GEN-LAST:event_BtnPesquisarNomeActionPerformed

    private void cxPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPrecoActionPerformed

    private void boxFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxFornecedorActionPerformed

    private void boxFornecedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_boxFornecedorAncestorAdded
        // Listar os fornecedores no combo box
        FornecedorDao dao = new FornecedorDao();
        //gerar lista de fornecedores
        List<Fornecedor> listadefornecedores = dao.listarFornecedores();
        //limpa o combo box toda vez que é aberto
        boxFornecedor.removeAll();
        //Gera os dados e coloca no combo box
        for(Fornecedor f : listadefornecedores){
                boxFornecedor.addItem(f);
        }
        
        
        
    }//GEN-LAST:event_boxFornecedorAncestorAdded

    private void boxFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxFornecedorMouseClicked
        // Para criar a opção de alterar o fornecedor
        FornecedorDao dao = new FornecedorDao();
        List<Fornecedor> listadefornecedores = dao.listarFornecedores();
        boxFornecedor.removeAllItems();
        
        for(Fornecedor f : listadefornecedores){
           boxFornecedor.addItem(f); 
        }
    }//GEN-LAST:event_boxFornecedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmproduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmproduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsultarProduto;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnPesquisarNome;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JTextField CxCodigo;
    private javax.swing.JTextField CxConsultaProduto;
    private javax.swing.JPanel PainelBusca;
    public javax.swing.JTabbedPane PainelDeAbas;
    private javax.swing.JPanel PainelEdicao;
    private javax.swing.JTable TabelaProdutos;
    private javax.swing.JComboBox boxFornecedor;
    private javax.swing.JTextField cxDescricao;
    private javax.swing.JTextField cxEstoque;
    private javax.swing.JTextField cxPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
