/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.ItemVendaDao;
import br.com.projeto.dao.ProdutosDao;
import br.com.projeto.dao.VendasDao;
import br.com.projeto.model.ItensVenda;
import br.com.projeto.model.Produto;
import br.com.projeto.model.Vendas;
import com.sun.prism.impl.PrismSettings;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edoom
 */
public class frmcontroleestoque extends javax.swing.JFrame {
    
    int idproduto, qtdenova;

    //método para listar na tabela
    public void listar(){
        //criar a lista de Produtos
        ProdutosDao dao = new ProdutosDao();
        List<Produto> lista = dao.listarProdutos();
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)tabelaControleEstoque.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Produto coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getDescricao(),
                coluna.getPreco(),
                coluna.getQtd_estoque(),
                coluna.getFornecedor().getNome()
            });
        }
    }
    
    public frmcontroleestoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnPesquisar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        BtnAdicionar = new javax.swing.JButton();
        cxDescricao = new javax.swing.JTextField();
        cxEstoqueAtual = new javax.swing.JTextField();
        cxQtde = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaControleEstoque = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Estoque");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(169, 199, 208));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Controle de Estoque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
        );

        jPanel2.setBackground(new java.awt.Color(199, 223, 226));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Descrição:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Estoque Atual:");

        BtnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnPesquisar.setText("Pesquisar");
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });
        BtnPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPesquisarKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Quantidade:");

        BtnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnAdicionar.setText("Adicionar");
        BtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarActionPerformed(evt);
            }
        });
        BtnAdicionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAdicionarKeyPressed(evt);
            }
        });

        cxDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cxDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDescricaoActionPerformed(evt);
            }
        });

        cxEstoqueAtual.setEditable(false);
        cxEstoqueAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cxEstoqueAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxEstoqueAtualActionPerformed(evt);
            }
        });

        cxQtde.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cxQtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxQtdeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cxEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cxQtde))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAdicionar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(BtnPesquisar)
                    .addComponent(cxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cxEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdicionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaControleEstoque.setBackground(new java.awt.Color(199, 223, 226));
        tabelaControleEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Preço", "Qtde Estoque", "Fornecedor"
            }
        ));
        tabelaControleEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaControleEstoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaControleEstoque);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
       //Botão pesquisar
        String nome = "%" + cxDescricao.getText() + "%";
        //criar a lista de clientes
        ProdutosDao dao = new ProdutosDao();
        List<Produto> lista = dao.listarProdutosPorNome(nome);
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)tabelaControleEstoque.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Produto coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getDescricao(),
                coluna.getPreco(),
                coluna.getQtd_estoque(),
                coluna.getFornecedor().getNome()             
            });
        }
    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void BtnPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPesquisarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPesquisarKeyPressed

    private void tabelaControleEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaControleEstoqueMouseClicked
        //pegar dados
        idproduto = Integer.parseInt(tabelaControleEstoque.getValueAt(tabelaControleEstoque.getSelectedRow(), 0).toString());
        cxDescricao.setText(tabelaControleEstoque.getValueAt(tabelaControleEstoque.getSelectedRow(), 1).toString());
        cxEstoqueAtual.setText(tabelaControleEstoque.getValueAt(tabelaControleEstoque.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tabelaControleEstoqueMouseClicked

    private void BtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarActionPerformed
        try {
            int estoque, qtdeatual;
            estoque = Integer.parseInt(cxEstoqueAtual.getText());
            
            qtdeatual = Integer.parseInt(cxQtde.getText());
                 
            qtdenova = estoque + qtdeatual;
            
            ProdutosDao dao = new ProdutosDao();
            dao.adicionarEstoque(idproduto, qtdenova);
            
            JOptionPane.showMessageDialog(null, "Estoque atualizado");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na atualização: "+ e);
        }
    }//GEN-LAST:event_BtnAdicionarActionPerformed

    private void BtnAdicionarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAdicionarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdicionarKeyPressed

    private void cxDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDescricaoActionPerformed

    private void cxEstoqueAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxEstoqueAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxEstoqueAtualActionPerformed

    private void cxQtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxQtdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxQtdeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmcontroleestoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmcontroleestoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmcontroleestoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmcontroleestoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmcontroleestoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionar;
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JTextField cxDescricao;
    private javax.swing.JTextField cxEstoqueAtual;
    private javax.swing.JTextField cxQtde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaControleEstoque;
    // End of variables declaration//GEN-END:variables
}
