
package br.com.projeto.view;

import br.com.projeto.dao.FornecedorDao;
import br.com.projeto.model.Fornecedor;
import br.com.projeto.model.Uteis;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edersom Denir Giacomelli
 */
public class frmfornecedores extends javax.swing.JFrame {
    
    //método para listar na tabela
    public void listar(){
        //criar a lista de clientes
       FornecedorDao dao = new FornecedorDao();
        List<Fornecedor> lista = dao.listarFornecedores();
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)TabelaFornecedores.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Fornecedor coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getNome(),
                coluna.getCnpj(),
                coluna.getEmail(),
                coluna.getTelefone(),
                coluna.getCelular(),
                coluna.getCep(),
                coluna.getEndereco(),
                coluna.getNumero(),
                coluna.getComplemento(),
                coluna.getBairro(),
                coluna.getCidade(),
                coluna.getEstado()             
            });
        }
    }

    /**
     * Creates new form frmcliente
     */
    public frmfornecedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PainelDeAbas = new javax.swing.JTabbedPane();
        PainelEdicao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CxCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CxNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CxEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CxCelular = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        CxTelefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        CxCep = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        CxEndereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CxNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CxBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CxCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CxComplemento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BoxEstado = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        CxCnpj = new javax.swing.JFormattedTextField();
        BtnPesquisarCnpj = new javax.swing.JButton();
        PainelBusca = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        CxConsulta = new javax.swing.JTextField();
        BtnConsultarNome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFornecedores = new javax.swing.JTable();
        BtnNovo = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedores");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(169, 199, 208));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Cadastro de Fornecedores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        PainelEdicao.setBackground(new java.awt.Color(199, 223, 226));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Código Fornecedor:");

        CxCodigo.setEditable(false);
        CxCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxCodigoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome fornecedor:");

        CxNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxNomeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("E-mail:");

        CxEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxEmailActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Celular:");

        try {
            CxCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CxCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Telefone Fixo:");

        try {
            CxTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CxTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CEP:");

        try {
            CxCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## . ### - ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CxCep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Endereço:");

        CxEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxEnderecoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nº:");

        CxNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxNumeroActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Bairro:");

        CxBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxBairroActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("UF:");

        CxCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxCidadeActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Complemento:");

        CxComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxComplementoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Cidade:");

        BoxEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RR", "RO", "RJ", "RN", "RS", "SC", "SP", "SE", "TO" }));
        BoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxEstadoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("CNPJ: ");

        try {
            CxCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## . ### . ### / #### - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CxCnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxCnpjActionPerformed(evt);
            }
        });

        BtnPesquisarCnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnPesquisarCnpj.setText("Pesquisar");
        BtnPesquisarCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarCnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelEdicaoLayout = new javax.swing.GroupLayout(PainelEdicao);
        PainelEdicao.setLayout(PainelEdicaoLayout);
        PainelEdicaoLayout.setHorizontalGroup(
            PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(CxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(CxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelEdicaoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(CxCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnPesquisarCnpj)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PainelEdicaoLayout.setVerticalGroup(
            PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelEdicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(CxCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CxCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(CxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CxComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(CxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(CxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CxCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPesquisarCnpj))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        PainelDeAbas.addTab("Dados do fornecedor", PainelEdicao);

        PainelBusca.setBackground(new java.awt.Color(199, 223, 226));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Nome:");

        CxConsulta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CxConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CxConsultaActionPerformed(evt);
            }
        });
        CxConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CxConsultaKeyPressed(evt);
            }
        });

        BtnConsultarNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnConsultarNome.setText("Pesquisar");
        BtnConsultarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsultarNomeActionPerformed(evt);
            }
        });
        BtnConsultarNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnConsultarNomeKeyPressed(evt);
            }
        });

        TabelaFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código:", "Nome:", "CNPJ:", "E-mail:", "Telefone Fixo:", "Celular:", "CEP:", "Endereço:", "nº:", "Complemento:", "Bairro:", "Cidade:", "UF:"
            }
        ));
        TabelaFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaFornecedores);

        javax.swing.GroupLayout PainelBuscaLayout = new javax.swing.GroupLayout(PainelBusca);
        PainelBusca.setLayout(PainelBuscaLayout);
        PainelBuscaLayout.setHorizontalGroup(
            PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelBuscaLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnConsultarNome)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        PainelBuscaLayout.setVerticalGroup(
            PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnConsultarNome))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        PainelDeAbas.addTab("Consultar Fornecedor", PainelBusca);

        BtnNovo.setBackground(new java.awt.Color(200, 200, 200));
        BtnNovo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnNovo.setForeground(new java.awt.Color(0, 0, 51));
        BtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo-documento.png"))); // NOI18N
        BtnNovo.setText("NOVO");
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BtnSalvar.setBackground(new java.awt.Color(200, 200, 200));
        BtnSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnSalvar.setForeground(new java.awt.Color(0, 0, 51));
        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar_1.png"))); // NOI18N
        BtnSalvar.setText("SALVAR");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnEditar.setBackground(new java.awt.Color(200, 200, 200));
        BtnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(0, 0, 51));
        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar (1).png"))); // NOI18N
        BtnEditar.setText("EDITAR");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnExcluir.setBackground(new java.awt.Color(200, 200, 200));
        BtnExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnExcluir.setForeground(new java.awt.Color(0, 0, 51));
        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir_1.png"))); // NOI18N
        BtnExcluir.setText("EXCLUIR");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelDeAbas)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(BtnNovo)
                .addGap(18, 18, 18)
                .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnEditar, BtnExcluir, BtnNovo, BtnSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelDeAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNovo)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnEditar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnEditar, BtnExcluir, BtnNovo, BtnSalvar});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxCodigoActionPerformed

    private void CxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxNomeActionPerformed

    private void CxEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxEmailActionPerformed

    private void CxEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxEnderecoActionPerformed

    private void CxNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxNumeroActionPerformed

    private void CxBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxBairroActionPerformed

    private void CxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxCidadeActionPerformed

    private void CxComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxComplementoActionPerformed

    private void CxConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxConsultaActionPerformed

    private void BtnConsultarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarNomeActionPerformed
        //Botão pesquisar
        String nome = "%" + CxConsulta.getText() + "%";
        //criar a lista de fornecedor
        FornecedorDao dao = new FornecedorDao();
        List<Fornecedor> lista = dao.buscarFornecedorPorNome(nome);
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)TabelaFornecedores.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Fornecedor coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getNome(),
                coluna.getCnpj(),
                coluna.getEmail(),
                coluna.getTelefone(),
                coluna.getCelular(),
                coluna.getCep(),
                coluna.getEndereco(),
                coluna.getNumero(),
                coluna.getComplemento(),
                coluna.getBairro(),
                coluna.getCidade(),
                coluna.getEstado()             
            });
        }
        
    }//GEN-LAST:event_BtnConsultarNomeActionPerformed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        // Botão novo - limpa a tela
        new Uteis().LimparTela(PainelEdicao);
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        //Botão excluir
            //vai pegar o nome que está nas caixas
            Fornecedor obj = new Fornecedor();
            obj.setId(Integer.parseInt(CxCodigo.getText()));
            
            FornecedorDao dao = new FornecedorDao();
            
            dao.excluirFornecedor(obj);
            
            new Uteis().LimparTela(PainelEdicao);
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        // botão salvar
            //vai pegar o nome que está nas caixas
            Fornecedor obj = new Fornecedor();
            obj.setNome(CxNome.getText());
            obj.setCnpj(CxCnpj.getText());
            obj.setEmail(CxEmail.getText());
            obj.setTelefone(CxTelefone.getText());
            obj.setCelular(CxCelular.getText());
            obj.setCep(CxCep.getText());
            obj.setEndereco(CxEndereco.getText());
            obj.setNumero(Integer.parseInt(CxNumero.getText()));
            obj.setComplemento(CxComplemento.getText());
            obj.setBairro(CxBairro.getText());
            obj.setCidade(CxCidade.getText());
            obj.setEstado(BoxEstado.getSelectedItem().toString());
            
            FornecedorDao dao = new FornecedorDao();
            
            dao.cadastrarFornecedor(obj);
            
            new Uteis().LimparTela(PainelEdicao);
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // Botão editar
            //vai pegar o nome que está nas caixas
            Fornecedor obj = new Fornecedor();
            obj.setNome(CxNome.getText());
            obj.setCnpj(CxCnpj.getText());
            obj.setEmail(CxEmail.getText());
            obj.setTelefone(CxTelefone.getText());
            obj.setCelular(CxCelular.getText());
            obj.setCep(CxCep.getText());
            obj.setEndereco(CxEndereco.getText());
            obj.setNumero(Integer.parseInt(CxNumero.getText()));
            obj.setComplemento(CxComplemento.getText());
            obj.setBairro(CxBairro.getText());
            obj.setCidade(CxCidade.getText());
            obj.setEstado(BoxEstado.getSelectedItem().toString());
            
            obj.setId(Integer.parseInt(CxCodigo.getText()));
            
            FornecedorDao dao = new FornecedorDao();
            
            dao.alterarFornecedor(obj);
            
            new Uteis().LimparTela(PainelEdicao);
        
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxEstadoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Carrega a lista
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void TabelaFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaFornecedoresMouseClicked
        //Pegar os dados
        //Faz voltar na tela de cadastro
        PainelDeAbas.setSelectedIndex(0);
        //Passar os dados da tabela para a tela de cadastro
        CxCodigo.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 0).toString());
        CxNome.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 1).toString());
        CxCnpj.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 2).toString());
        CxEmail.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 3).toString());
        CxTelefone.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 4).toString());
        CxCelular.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 5).toString());
        CxCep.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 6).toString());
        CxEndereco.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 7).toString());
        CxNumero.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 8).toString());
        CxComplemento.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 9).toString());
        CxBairro.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 10).toString());
        CxCidade.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 11).toString());
        BoxEstado.setSelectedItem(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 12).toString());
    }//GEN-LAST:event_TabelaFornecedoresMouseClicked

    private void CxConsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CxConsultaKeyPressed
       //consulta apenas digitando
       String nome = "%" + CxConsulta.getText() + "%";
        //criar a lista de clientes
        FornecedorDao dao = new FornecedorDao();
        List<Fornecedor> lista = dao.buscarFornecedorPorNome(nome);
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)TabelaFornecedores.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Fornecedor coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getNome(),
                coluna.getCnpj(),
                coluna.getEmail(),
                coluna.getTelefone(),
                coluna.getCelular(),
                coluna.getCep(),
                coluna.getEndereco(),
                coluna.getNumero(),
                coluna.getComplemento(),
                coluna.getBairro(),
                coluna.getCidade(),
                coluna.getEstado()             
            });
        }       
    }//GEN-LAST:event_CxConsultaKeyPressed

    private void BtnPesquisarCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarCnpjActionPerformed
        // Botão de pesquisa por CNPJ
            String cnpj = CxCnpj.getText();
            Fornecedor obj = new Fornecedor();
            FornecedorDao dao = new FornecedorDao();
            
            obj = dao.consultarPorCnpj(cnpj);
            
            //Exibição de dados nos campos
            if (obj.getCnpj() != null) {
            CxCodigo.setText(String.valueOf(obj.getId()));
            CxNome.setText(obj.getNome());
            CxCnpj.setText(obj.getCnpj());
            CxEmail.setText(obj.getEmail());
            CxTelefone.setText(obj.getTelefone());
            CxCelular.setText(obj.getCelular());
            CxCep.setText(obj.getCep());
            CxEndereco.setText(obj.getEndereco());
            CxNumero.setText(String.valueOf (obj.getNumero()));
            CxComplemento.setText(obj.getComplemento());
            CxBairro.setText(obj.getBairro());
            CxCidade.setText(obj.getCidade());
            BoxEstado.setSelectedItem(obj.getEstado());
            }
            if (obj.getCnpj() == null) {
                JOptionPane.showMessageDialog(null, "Fornecedor não localizado!!!");
            }
    }//GEN-LAST:event_BtnPesquisarCnpjActionPerformed

    private void CxCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CxCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CxCnpjActionPerformed

    private void BtnConsultarNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnConsultarNomeKeyPressed
        //consulta apenas digitando
       String nome = "%" + CxConsulta.getText() + "%";
        //criar a lista de clientes
        FornecedorDao dao = new FornecedorDao();
        List<Fornecedor> lista = dao.buscarFornecedorPorNome(nome);
        //Uso default table model para pegar o padrão da tabela
        DefaultTableModel dados = (DefaultTableModel)TabelaFornecedores.getModel();
        //limpar os dados
        dados.setNumRows(0);
        //colocar dados na lista - para cada item uma linha - definindo ordem
        for(Fornecedor coluna : lista){
            dados.addRow(new Object[]{
                coluna.getId(),
                coluna.getNome(),
                coluna.getCnpj(),
                coluna.getEmail(),
                coluna.getTelefone(),
                coluna.getCelular(),
                coluna.getCep(),
                coluna.getEndereco(),
                coluna.getNumero(),
                coluna.getComplemento(),
                coluna.getBairro(),
                coluna.getCidade(),
                coluna.getEstado()             
            });
        }
        
    }//GEN-LAST:event_BtnConsultarNomeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmfornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmfornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmfornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmfornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmfornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxEstado;
    private javax.swing.JButton BtnConsultarNome;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnPesquisarCnpj;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JTextField CxBairro;
    private javax.swing.JFormattedTextField CxCelular;
    private javax.swing.JFormattedTextField CxCep;
    private javax.swing.JTextField CxCidade;
    private javax.swing.JFormattedTextField CxCnpj;
    private javax.swing.JTextField CxCodigo;
    private javax.swing.JTextField CxComplemento;
    private javax.swing.JTextField CxConsulta;
    private javax.swing.JTextField CxEmail;
    private javax.swing.JTextField CxEndereco;
    private javax.swing.JTextField CxNome;
    private javax.swing.JTextField CxNumero;
    private javax.swing.JFormattedTextField CxTelefone;
    private javax.swing.JPanel PainelBusca;
    private javax.swing.JTabbedPane PainelDeAbas;
    private javax.swing.JPanel PainelEdicao;
    private javax.swing.JTable TabelaFornecedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
